# America's Contested Covenant

What binds us together as Americans? What makes us not just a collection
of individuals, but a nation?

We share icons. The pages of my jumbo-sized passport are dyed with
images of The Liberty Bell, The Declaration of Independence,
Independence Hall, farmers navigating teams of oxen, Mount Rushmore,
cacti catching a southwestern desert sky, a grizzly seizing a salmon
underneath the guard of a northwest native American totem pole.

Above these images hang quotes from great American fathers. Horace
Greeley urges an unnamed protege to "Go West, young man, and grow up
with the country." Thomas Jefferson. Even Ronald Reagan makes an
appearance. (The halls of this particular American Valhalla seem extra
busy with the voices of White Christian men.)

These quoted words, these images, together urge on us a story. We are,
they reassure us, a nation.

Perhaps even more fundamental than the specifics of the story is the
reassuring message that *there is a story*. America has a story that
makes sense. By this story, we can make sense of ourselves. We can
locate ourselves in relation to our past, to our neighbors, to the
landscape.

"We tell ourselves stories in order to live." So wrote Joan Didion, an
American writer whose insightful analysis of 20th Century America has
inspired many but who has not, thus far, been honored with her own entry
in the pages of a passport book. At least, not a passport of the
official kind recognized by border control agents.

"If you don't have borders you don't have a country." So offered another
commentator on the American condition, Donald Trump. He missed the
point. A nation's borders are far less important than its defining
narratives -- the stories its people tell themselves about who they are.

America is having trouble these days. We can't decide together which
story we are living in. Which script we are reading from. Whose
inspiring quotes we are quoting to one another.

It's like we've each been issued a passport with thousands of pages.
Many pages offer us lovely, uplifting language by some statesman or
-woman, some writer, some public figure. Each page inspires, persuades,
provokes, uplifts. But we are having trouble, more and more trouble,
finding the common story that ties all these messages together.

Each of us can rifle the pages. We read messages that tell us each who
we are and what kind of nation we are. They seem important. We want to
understand. We start to piece together a story that makes sense to us.

Confused, excited, anxious about getting it wrong, we reach out and find
others who have attempted this task of story crafting, of finding
coherence, of making sense. When we find a group who seems ahead of us
in the game, we are overjoyed, relieved. We are making it work. We are
indeed a tribe. We have a story together. Therefore, we are a nation.

Then we run into apostates. People who have focused on other pages in
their passports.

A central confusion in the U.S. today concerns the disputed terms of our
unwritten social covenant, and confusion over the difference between our
covenant and our Constitution.

### The U.S. has a *de facto* social covenant

The U.S. has a written social contract: the Constitution.

The U.S. has an *unwritten* social covenant. In fact, more than one.

Our social covenant is spread over a few places: The Declaration of
Independence. The Preamble to the Constitution. The Bill of Rights. The
Pledge of Allegiance.

### The social covenant of the U.S. is *contested*

Some basic terms of our social covenant have never been settled.

Who is a full member of the community?

The original Constitution of the United States does not clarify who,
exactly, is a citizen of this new nation.

What are the rights and obligations of community members to one another?

What role does religion and religious scripture hold in setting the
terms of the covenant -- if any?
