---
title: "The Social Covenant of Democracy"
author: "Athena Small"
format: revealjs
editor: visual
---

## 

Thank you all for coming. I am honored to be here.

I'd like to speak with you today about some ideas I've been thinking about.

When I meet people in Ukraine, I find that nearly always they ask me, Why are you here in Ukraine? Why did you come here during wartime? Aren't you afraid?

On the question of whether I am afraid, that question I can address simply. No, I am not afraid. It's to me a fairly simple calculation about risk. Kyiv is the 7th largest city in Europe, now well-defending by missile defense systems. There are, very sadly and outrageously, people in Kyiv who are harmed, injured, even killed by Russian missile and drone attacks. But in a city of over twelve million, the number who are actually physically harmed or killed by these attacks number, over the course of a year, in the dozens. One would have to be very very very unlucky to be one of the ones who is injured or killed. I find this risk to be small -- not large enough to make it drive my decisions about where to go, what to do.

If the mood seems right, I may also note that we have in the USA also a terrible plague of gun violence, one that is self-inflicted. Several times each week, someone in the U.S. goes on a rampage of murder, killing several of their fellow citizens and residents. I am interested in learning from the data whether the risk of gun violence in the U.S. isn't actually worse than the risk of injury or death in Ukraine from Russian attacks. I don't know which is larger. But I expect the scales are comparable.

In other words, I may actually be physically safer in Kyiv than in, say, Philadelphia or Denver.

The more interesting question is the first one: Why am I here? Why am I here now?

Here's the very short answer: I am here to help in the fight for democracy.

As I see it, Russia's assault on Ukraine is an assault by an authoritarian state on a democratic society. It is one front in a world war. A war of authoritarianism against democracy that is underway right now across the entire world.

To me, democracy is precious. More than precious: democracy is *sacred*. Democracy is a system that offers the credible promise of allowing human beings to flourish, fully.

A generation ago, at the end of the Cold War, many foolishly believed that, in the grinding conflict of ideologies and political systems, liberal democracy had triumphed, decisively, definitively. There was some mopping up to do, of course. But in the large scheme of things, we had reached, in this telling, The End of History.

Of course, history did not get the memo.

Why is liberal democracy under such apparent threat now, a generation later?

There are many stories that can be told, of course. I'd like to talk about how we got democracy wrong, and how we can get it right. Before it's too late.

## Social Contract Theory

Every society is held together by stories. Stories about who its people are, what obligations they owe to one another, what kind of good
