project:
  type: book
  output-dir: docs

book:
  title: "The Social Covenant of Democracy"
  author: "Athena Small"
  date: "2024"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-What_is_a_social_covenant.qmd
    - 03-current-us-covenant.qmd
    - part: "Part I: Social Covenants in Scripture and in History"
      chapters: 
        - 04-divine-covenants.qmd
        - 05-greco-roman-covenants.qmd
        - 06-medieval-early-modern.qmd
    - part: "Part II: The Enlightenment Project"
      chapters:
      - 07-enlightenment-social-contract.qmd
    - part: "Part III: Designing a Social Covenant for an Enlightened Liberal Democracy"
    - 99-references.qmd

    # - part: "Part I"
    #   chapters: 
    #   - chapter.qmd
    #   - antoher-chapter.qmd
    # - part: "Part II"
    #   chapters:
    #   - yet-another-chapter.qmd

# bibliography: the-social-covenant.bib
bibliography: [The_Social_Covenant.bib, book.bib]
# biblio-style: apalike
# link-citations: true
# description: ""

format:
  html:
    theme: cosmo
    toc: true

editor: visual


    
