project:
  type: book
  output-dir: docs

book:
  title: "The Social Covenant of Democracy"
  author: "Athena Small"
  date: "2024"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-What_is_a_social_covenant.qmd
    - 03-current-us-covenant.qmd
    - part: "Part I: Social Covenants in Scripture and in History"
      chapters: 
        - 04-divine-covenants.qmd
        - 05-greco-roman-covenants.qmd
        - 06-medieval-early-modern.qmd
    - part: "Part II: The Enlightenment Project"
      chapters:
      - 07-enlightenment-social-contract.qmd
    - part: "Part III: The Social Covenant of the United States of America"
      # chapters:
      # - contract-covenant-constitution.qmd
      # - originalism.qmd
      # - indigenous-critique.qmd
      # - black-critique.qmd
      # - libertarian-option.qmd
      # - christian-nationalist-option.qmd
    - part: "Part IV: Designing a Social Covenant for an Enlightened Liberal Democracy"
    - part: "Part V: What Next?"
    - 99-references.qmd


# bibliography: the-social-covenant.bib
bibliography: [The_Social_Covenant.bib, book.bib]
# biblio-style: apalike
# link-citations: true
# description: ""

format:
  html:
    theme: cosmo
    toc: true

editor: visual


    
