---
# biblio-style: apalike
# link-citations: true
# description: ""
---

# Foreward {.unnumbered}

The peaceful transfer of power from one legitimately elected regime to
another is non-negotiable hallmark of democracy. In the United States
this tradition has been honored in an unbroken chain from the very first
transfer, in 1797, when George Washington willingly stepped down to hand
the reins of the presidency to his elected successor, John Adams.

Until January 6, 2021, when, shockingly, the chain snapped.

===

\[Fill out the paragraph below after reviewing first-hand reports about
the events of Jan. 6.\]

-   Assault insurrection Jan 6, 2021
    -   Graphical description. Bear spray. assault weapons. zip ties. 6
        deaths, noose. after pelosi, aoc, ...
    -   Crouching on the floor. texting spouses. blockading the front
        door with guns...
-   Quote(s) from the four Capitol Police officers. Astonishment that
    the insurrection happened, and that there is no consensus
    description of what happened.

===

January 6, 2021, was a singular event. But it did not come out of the
blue. It was shocking, but not surprising. Everything depends on whether
we can unveil the antecedent conditions that enabled, and eventually
made inevitable, this rupture. Everything depends on uncovering the
correct understanding of what brought us to this point.

We are living through a breakdown of American political civil society.
Enflamed by fears of losing their traditional dominance, and ashamed of
losing that dominance to coastal elites, brown people, and immigrants,
one-third of the American people are jettisoning democracy and embracing
fascism.

The forces that brought us to this crisis are not recent. They are
deeply rooted in American history, and even our pre-history. Finding our
way to a healthier America requires looking way back to the ideas and
forces that brought us this sickness.

This book is motivated by three questions. How did this happen? How did
we get to this place? And perhaps most important: How do we get out of
it?

===

A sneak preview of our conclusions is warranted.

We are living now through one of the most alarming periods in American
history. There is much grounds for feeling pessimism.

Yet we believe there is a way forward to a better America, founded on a
new social covenant.

------------------------------------------------------------------------

## What the hell is happening to America?

Just one generation ago, the United States of America appeared to reign
supreme. The U.S. had, unambiguously, won the Cold War. We had not only
the world's largest military and economy. We had *confidence*. We had
coherence. We knew who we were. We had continuing problems - but we had
also the resources, the will, the vision to address these problems.
There seemed nothing we could not do. American leadership in the world
was barely challenged.

\[Maybe pick a specific day to mark the apex of U.S. global political
power and self-confidence. Maybe Clinton's First Inauguration.\]

Fast-forward to 2024. Incredibly, the Republican Party, the party of
Eisenhower, of Reagan, of George H.W. Bush, has abandoned its commitment
to NATO and embraced, as its unchallenged leader, a sex offender, a
felon, a crime boss, a liar, a blow hard, a deeply unserious person with
no interest in policy, no interest in America's security, no interest in
anything but his own self-interest.

What the hell happened?

Many explanations have been offered. We spent too much time on our
smartphones. We forgot how to read. We neglected Jesus. We played too
many video games. We raised our kids without discipline. We let in too
many immigrants. Women aren't focused on raising the kids. We watched
too much Fox News. Etc.

We think that the answer is more fundamental than any of these stories
would allow. We believe the answer to the question, What the hell
happened to America, turns on a fundamental question of what America is.

What holds the United States together as a unity is not a shared ethnic
heritage, a specific territory, a ruling royal family or aristocracy, a
coat of arms, an epic poem, or any of the other cultural bindings that
work to hold together our neighbors on the world stage.

More than any other nation, the United States of America is a nation
founded on *ideas. "We hold these truths to be self-evident, that all
men are created equal. That they are endowed with certain unalienable
rights. That among these are life, liberty, and the pursuit of
happiness."*

At our birth, we embraced and celebrated these noble ideals, and
announced them to the entire world. We told ourselves, we told the
world, that these ideals — *universal* ideals of *universal* human
rights — would serve as the foundation of our new polity.

Though the poetry is riveting, these ideas did not spring fully formed
and fresh from the mind of Thomas Jefferson. Jefferson's pen dipped deep
into a tradition that was by then already more than a century old, and
ripe. Jefferson was channeling the innovators of a new model of politics
called *social contract theory.*

## Social contract theory: The philosophical foundation of the United States

## So what's wrong with that?

We adopted a model in which the nation is held together as a
transactional *deal* based on mutually-supporting self-interest. It is
ironically, if tragically, appropriate that we would elevate a leader
who embodies this ideal pursuit of self-interest perfectly.

We adopted a philosophy of governance based on self-interest. Then we
adopted a Constitution that, in order to function properly, required a
large number of statesmen who would set aside their self-interest in
service to the nation.

We never adequately address this contradiction. We never wrote a set of
founding documents in which the principles of our government aligned
with the type of people who would run this government. We assumed a
nation of greedy self-interested assholes, then called on them to
sacrifice their self-interest for the good of the nation.

What's amazing is not that it failed. What's amazing is that it worked
for so long. That the momentum of Revolutionary-era virtue carried us
forward all the way into the 21st Century. We had a better run that our
Founding Flaws deserved.

## What now?

To survive and thrive as a nation, we must address the flaws in our
founding national story.

We
