# Christian Nationalism

The Enlightenment ideals of the United States has today no more potent
rival than Christian Nationalism. This ideology can claim powerful
assets: tens of millions of adherents; an expansive network of
institutions, colleges, think tanks, and other forms of well-funded
organizational infrastructure; some historical legitimacy, though
imperfect, to underpin their claims; and an energized community of
leaders.

Although no one truly takes seriously the notion that Donald Trump is
actually a Christian, he is welcomed by the Christian Nationalist
movement as a valued transactional ally.

The United States of America began with roots planted in the social
contract theory of the enlightenment.

@achrist

@AutocraticLegalismUniversity

## The Christian Nationalist Covenant

A Christian Nationalist covenant for the United States would incorporate
some of the following elements.

-   It might accept that the proper role of government is to promote
    human flourishing. But it would assert that humans can only flourish
    truly and fully when they accept Jesus Christ as their lord and
    savior. A government should, therefore, create the conditions for a
    truly Christian community.

-   Christian Nationalists generally assert that the United States was
    "founded as a Christian nation."

-   Commonly, American Christian Nationalists will assert that God
    chose, marked out and set apart the United States to play a special
    role in the world. In this telling, Christian America is the
    successor to Jewish Israel. America is *not* special because it was
    the first nation founded on the universal democratic ideals of the
    Enlightenment. It is special because it is distinct from all other
    nations in its special role, chosen for it by God.

This description has a Protestant accent, insofar as it emphasizes the
central importance of a *personal* relationship between the individual
believer and Jesus as Lord.

A Catholic version of a Christian Nationalist covenant would assign a
central role to the hierarchical authority of the Roman Catholic Church.
Examples of Catholic Nationalist covenants include those governing the
autocracy of Franco's Spain, and the theocracy of the earlier Irish
Republic.

In fact, Christian Nationalists have been quite clear and specific about
their plans and their programs.

## Dominionism

What distinguishes Christian Nationalism from conservative Christian
belief?

The difference is this: Christian Nationalism incorporates a will to
control and wield state power, broadly.

Dominionism is a set of beliefs and a program, aimed at Christian
hegemony over the United States. Dominionism identifies seven
"mountains", or domains of influence: family, government, law, academia,
media, business, and \[X\]. The program calls for conservative
Christians to control all seven of these domains, in order to control
society.

(Lenin analogously referenced "the commanding heights" of the economy
over which the Bolshevik party must retain control.)

## Christian Nationalism and Christian Belief

It seems so obvious that one wonders if it even needs stating. But let
there be no doubt remaining: Christian Nationalism has only the thinnest
filaments of connection to actual Christian belief.

Homosexuality was well known in the ancient Near East. Yet as far as the
written sources record, Jesus never said anything at about gay people.
Jesus said nothing about abortion.

What Jesus spoke about, relentlessly, was love. He commanded us to love
God above all else, and to love our neighbors as ourselves.

If we were actually a Christian Nation, we would use government to make
sure that every child is fed, housed, educated, and insured. We would
make sure that all our neighbors, of any faith or of none, felt welcome.
An actual Christian nation would look very much like a multiracial,
multicultural social democracy.
